funcptr1.out : funcptr1.c
	gcc funcptr1.c -ansi -Wall -pedantic -o funcptr1.out
funcptr2.out : funcptr2.c
	gcc funcptr2.c -ansi -Wall -pedantic -o funcptr2.out
funcptr3.out : funcptr3.c
	gcc funcptr3.c -ansi -Wall -pedantic -o funcptr3.out